IPbox/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from IPbox import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    
    path('', views.ipboxHomePage, name='homepage'),
    path('sites/', include('siteapp.urls')),
    path('racks/', include('rackapp.urls')),
    path('blades/', include('bladeapp.urls')),
    path('slots/', include('slotapp.urls')),
    path('vms/', include('vmapp.urls')),
    path('clusters/', include('clusterapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rackapp/urls.py
from django.urls import path
from . import views

# TEMPLATE TAGGING
app_name = 'rackapp'

urlpatterns = [
  path('create', views.rackCreate, name='rack_create'),
  path('update/<id>', views.rackUpdate, name='rack_update'),
  path('rackquery/<id>', views.rackQuery, name='rack_query'),
  path('', views.rackList, name="racks"),
]

siteapp/urls.py
from django.urls import path
from . import views

# TEMPLATE TAGGING
app_name = 'siteapp'

urlpatterns = [
  path('create', views.siteCreate, name='site_create'),
  path('update/<id>', views.siteUpdate, name='site_update'),
  path('sitequery/<id>', views.siteQuery, name='site_query'),
  path('', views.siteList, name="sites"),
]

rackapp/models.py
from django.db import models
from siteapp.models import Site


class Rack(models.Model):
  name  = models.CharField(max_length=128)
  ip    = models.GenericIPAddressField()
  site  = models.ForeignKey(Site, related_name="racks", on_delete=models.CASCADE)

  class Meta:
    verbose_name_plural = "Racks"

  def __str__(self):
    return self.name

rackapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator
from django.urls import reverse

from accounts.views import generalUser, adminUser
from siteapp.models import Site
from .models import Rack


def rackList(request):
  dataPerPage = 5
  pageNum = request.GET.get('page', 1)
  racks = Rack.objects.all()

  p = Paginator(racks, dataPerPage)
  page_obj = p.page(pageNum)

  context = {
    'page_obj': page_obj,
    'generalUser': generalUser(request.user),
    'adminUser': adminUser(request.user)
  }
  return render(request, 'rackapp/racks.html', context=context)


@login_required(login_url='accountsapp:login')
def rackCreate(request):
  if not adminUser(request.user):
    return HttpResponseRedirect(reverse('homepage'))
  
  if (request.POST):
    name    = request.POST['rackname']
    ip      = request.POST['rackip']
    siteid  = request.POST['site']
        
    site    = Site.objects.get(pk=siteid)

    rack    = Rack(name=name, ip=ip, site=site)
    rack.save()
    return redirect("/racks")

  context = {
    'sites': Site.objects.all()
  }
  return render(request, 'rackapp/rack_create.html', context=context)


@login_required(login_url='accountsapp:login')
def rackUpdate(request, id):
  if not adminUser(request.user):
    return HttpResponseRedirect(reverse('homepage'))

  rack = Rack.objects.get(pk=id)
  if (request.POST):
    name    = request.POST['rackname']
    ip      = request.POST['rackip']
    # siteid  = request.POST['site']
    # site = Site.objects.get(pk=siteid)
        
    rack.name = name
    rack.ip = ip
    # rack.site = site
    rack.save()
    return redirect("/racks")
    
  context = {
    'rack': rack,
    'sites': Site.objects.all()
  }
  return render(request, 'rackapp/rack_update.html', context=context)


@login_required(login_url='accountsapp:login')
def rackQuery(request, id):
  rack = Rack.objects.get(pk=id)

  dataPerPage = 5
  pageNum = request.GET.get('page', 1)
  blades = rack.blades.all()

  p = Paginator(blades, dataPerPage)
  page_obj = p.page(pageNum)

  context = {
    'page_obj': page_obj,
  }
  return render(request, 'bladeapp/blades.html', context)

rackapp/templates/rackapp/rack_create.html
{% extends 'sbadmin/base.html' %} {% load static %} {% block content %}

<div class="card-body">
  <div class="container my-4">
    <h3 class="my-4">Create Rack</h3>
    <form method="POST" action="{% url 'rackapp:rack_create' %}">
      {% csrf_token %}

      <div class="form-group row">
        <label for="rackname" class="col-sm-2 col-form-label">Name</label>
        <div class="col">
          <input
            type="text"
            class="form-control"
            id="rackname"
            name="rackname"
            required
          />
        </div>
      </div>
      <div class="form-group row">
        <label for="rackip" class="col-sm-2 col-form-label">IP</label>
        <div class="col">
          <input
            type="text"
            class="form-control"
            id="rackip"
            name="rackip"
            required
          />
        </div>
      </div>
      <div class="form-group row">
        <label for="site" class="col-sm-2 col-form-label">Site</label>
        <div class="col">
          <select class="custom-select" id="site" name="site" required>
            <option value="" selected>choose site...</option>
            {% for site in sites %}
            <option value="{{ site.id }}">{{ site.name }}</option>
            {% endfor %}
          </select>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-sm-2"></div>
        <div class="col">
          <div class="row">
            <div class="col-3">
              <a href="{% url 'rackapp:racks' %}" class="btn btn-warning btn-sm btn-block"
                >GO TO RACK LIST</a
              >
            </div>
            <div class="col">
              <button type="submit" class="btn btn-primary btn-sm btn-block">
                CREATE
              </button>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>

{% endblock content %}

rackapp/templates/rackapp/rack_update.html
{% extends 'sbadmin/base.html' %} {% load static %} {% block content %}

<div class="card-body">
  <div class="container my-4">
    <h3 class="my-4">Update Rack</h3>
    <form method="POST" action="{% url 'rackapp:rack_update' rack.id %}">
      {% csrf_token %}

      <div class="form-group row">
        <label for="rackname" class="col-sm-2 col-form-label">Name</label>
        <div class="col">
          <input
            type="text"
            class="form-control"
            value="{{ rack.name }}"
            id="rackname"
            name="rackname"
            required
          />
        </div>
      </div>
      <div class="form-group row">
        <label for="rackip" class="col-sm-2 col-form-label">IP</label>
        <div class="col">
          <input
            type="text"
            class="form-control"
            value="{{ rack.ip }}"
            id="rackip"
            name="rackip"
            required
          />
        </div>
      </div>
      <div class="form-group row">
        <label for="site" class="col-sm-2 col-form-label">Site</label>
        <div class="col">
          <select class="custom-select" id="site" name="site" disabled required>
            <option value="">choose site...</option>
            {% for site in sites %}
              <option value="{{ site.id }}" {% if rack.site.id == site.id %} selected {% endif %}>{{ site.name }}</option>
            {% endfor %}
          </select>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-sm-2"></div>
        <div class="col">
          <div class="row">
            <div class="col-3">
              <a href="{% url 'rackapp:racks' %}" class="btn btn-warning btn-sm btn-block"
                >GO TO RACK LIST</a
              >
            </div>
            <div class="col">
              <button type="submit" class="btn btn-primary btn-sm btn-block">
                UPDATE
              </button>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>

{% endblock content %}

rackapp/templates/rackapp/racks.html
{% extends 'sbadmin/base.html' %}{% load static %} {% block content %}

<!-- page heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h5 mb-0 text-gray-800">
    <a href="{% url 'siteapp:sites' %}">Site<a/> / Rack
  </h1>
</div>

<!-- table data -->
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary"><i class="fas fa-table mr-2"></i> Rack List</h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table
        class="table table-bordered"
        id="dataTable"
        width="100%"
        cellspacing="0"
      >
        <thead>
          <tr>
            <th>#</th>
            <th>Name</th>
            <th>IP</th>
            <th>Site</th>
            <th></th>
          </tr>
        </thead>
        <tfoot>
          <tr>
            <th></th>
            <th>Name</th>
            <th>IP</th>
            <th>Site</th>
            <th>
              {% if adminUser %}
                <a href="{% url 'rackapp:rack_create' %}" class="btn btn-primary btn-sm btn-block">CREATE RACK</a>
              {% else %}
                <div class="btn btn-primary btn-sm btn-block disabled customNotAllowed">CREATE RACK</div>
							{% endif %}
            </th>
          </tr>
        </tfoot>
        <tbody>
          {% for rack in page_obj %}
          <tr>
            <td>{{ forloop.counter }}</td>
            <td>
              <a href="{% url 'rackapp:rack_query' rack.id %}"
                class="text-primary">
                {{ rack.name }}
              </a>
            </td>
            <td>{{ rack.ip }}</td>
            <td>
              <a href="{% url 'siteapp:site_query' rack.site.id %}"
                class="text-primary">
                {{ rack.site.name }}
              </a>
            </td>

            <td class="text-center">
              {% if adminUser %}
                <a href="{% url 'rackapp:rack_update' rack.id %}"
                  class="text-info mr-4" title="edit">
                  <i class="fas fa-edit"></i>
                </a>

                <a href="#" class="text-danger ml-4" title="delete">
                  <i class="fas fa-trash-alt"></i>
                </a>
              {% else %}
                <!-- non-admin user -->
                <span class="text-info mr-4 customNotAllowed" title="edit">
                  <i class="fas fa-edit"></i>
                </span>
  
                <span class="text-danger ml-4 customNotAllowed" title="delete">
                  <i class="fas fa-trash-alt"></i>
                </span>
              {% endif %}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      {% include 'core/pagination.html' %}

    </div>
  </div>
</div>

{% endblock content %}