IPbox/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from IPbox import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    
    path('', views.ipboxHomePage, name='homepage'),
    path('sites/', include('siteapp.urls')),
    path('racks/', include('rackapp.urls')),
    path('blades/', include('bladeapp.urls')),
    path('slots/', include('slotapp.urls')),
    path('vms/', include('vmapp.urls')),
    path('clusters/', include('clusterapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bladeapp/urls.py
from django.urls import path
from . import views

# TEMPLATE TAGGING
app_name = 'bladeapp'

urlpatterns = [
  path('create', views.bladeCreate, name='blade_create'),
  path('update/<id>', views.bladeUpdate, name='blade_update'),
  path('bladequery/<id>', views.bladeQuery, name='blade_query'),
  path('', views.bladeList, name="blades"),
]

rackapp/urls.py
from django.urls import path
from . import views

# TEMPLATE TAGGING
app_name = 'rackapp'

urlpatterns = [
  path('create', views.rackCreate, name='rack_create'),
  path('update/<id>', views.rackUpdate, name='rack_update'),
  path('rackquery/<id>', views.rackQuery, name='rack_query'),
  path('', views.rackList, name="racks"),
]

siteapp/urls.py
from django.urls import path
from . import views

# TEMPLATE TAGGING
app_name = 'siteapp'

urlpatterns = [
  path('create', views.siteCreate, name='site_create'),
  path('update/<id>', views.siteUpdate, name='site_update'),
  path('sitequery/<id>', views.siteQuery, name='site_query'),
  path('', views.siteList, name="sites"),
]

bladeapp/models.py
from django.db import models
from siteapp.models import Site
from rackapp.models import Rack


class Blade(models.Model):
  name    = models.CharField(max_length=128)
  ip      = models.GenericIPAddressField()
  rack    = models.ForeignKey(Rack, related_name="blades", on_delete=models.CASCADE)

  class Meta:
    verbose_name_plural = "Blades"

  def __str__(self):
    return self.name

bladeapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator
from django.urls import reverse

from accounts.views import generalUser, adminUser
from siteapp.models import Site
from rackapp.models import Rack
from .models import Blade


def bladeList(request):
  dataPerPage = 5
  pageNum = request.GET.get('page', 1)
  blades = Blade.objects.all()

  p = Paginator(blades, dataPerPage)
  page_obj = p.page(pageNum)

  context = {
    'page_obj': page_obj,
    'generalUser': generalUser(request.user),
    'adminUser': adminUser(request.user)
  }
  return render(request, 'bladeapp/blades.html', context)


@login_required(login_url='accountsapp:login')
def bladeCreate(request):
  if not adminUser(request.user):
    return HttpResponseRedirect(reverse('homepage'))
  
  if (request.POST):
    name    = request.POST['bladename']
    ip      = request.POST['bladeip']
    rackid  = request.POST['rack']
        
    rack    = Rack.objects.get(pk=rackid)

    blade   = Blade(name=name, ip=ip, rack=rack)
    blade.save()
    return redirect("/blades")

  context = {
    'racks': Rack.objects.all()
  }
  return render(request, 'bladeapp/blade_create.html', context=context)


@login_required(login_url='accountsapp:login')
def bladeUpdate(request, id):
  if not adminUser(request.user):
    return HttpResponseRedirect(reverse('homepage'))
  
  blade = Blade.objects.get(pk=id)
  if (request.POST):
    name    = request.POST['bladename']
    ip      = request.POST['bladeip']
    rackid  = request.POST['rack']

    rack = Rack.objects.get(pk=rackid)
    
    blade.name = name
    blade.ip = ip
    blade.rack = rack
    blade.save()
    return redirect("/blades")
    
  context = {
    'blade': blade,
    'racks': Rack.objects.all()
  }
  return render(request, 'bladeapp/blade_update.html', context=context)


@login_required(login_url='accountsapp:login')
def bladeQuery(request, id):
  blade = Blade.objects.get(pk=id)

  dataPerPage = 5
  pageNum = request.GET.get('page', 1)
  slots = blade.slots.all()

  p = Paginator(slots, dataPerPage)
  page_obj = p.page(pageNum)

  context = {
    'page_obj': page_obj,
  }
  return render(request, 'slotapp/slots.html', context)

bladeapp/templates/bladeapp/blade_create.html
{% extends 'sbadmin/base.html' %} {% load static %} {% block content %}

<div class="card-body">
  <div class="container my-4">
    <h3 class="my-4">Create Blade</h3>
    <form method="POST" action="{% url 'bladeapp:blade_create' %}">
      {% csrf_token %}

      <div class="form-group row">
        <label for="bladename" class="col-sm-2 col-form-label">Name</label>
        <div class="col">
          <input
            type="text"
            class="form-control"
            id="bladename"
            name="bladename"
            required
          />
        </div>
      </div>
      <div class="form-group row">
        <label for="bladeip" class="col-sm-2 col-form-label">IP</label>
        <div class="col">
          <input
            type="text"
            class="form-control"
            id="bladeip"
            name="bladeip"
            required
          />
        </div>
      </div>
      <div class="form-group row">
        <label for="rack" class="col-sm-2 col-form-label">Rack</label>
        <div class="col">
          <select class="custom-select" id="rack" name="rack" required>
            <option value="" selected>choose rack...</option>
            {% for rack in racks %}
            <option value="{{ rack.id }}">{{ rack.name }}</option>
            {% endfor %}
          </select>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-sm-2"></div>
        <div class="col">
          <div class="row">
            <div class="col-3">
              <a href="{% url 'bladeapp:blades' %}" class="btn btn-warning btn-sm btn-block"
                >GO TO BLADE LIST</a
              >
            </div>
            <div class="col">
              <button type="submit" class="btn btn-primary btn-sm btn-block">
                CREATE
              </button>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>

{% endblock content %}

bladeapp/templates/bladeapp/blade_update.html
{% extends 'sbadmin/base.html' %} {% load static %} {% block content %}

<div class="card-body">
  <div class="container my-4">
    <h3 class="my-4">Update Blade</h3>
    <form method="POST" action="{% url 'bladeapp:blade_update' blade.id %}">
      {% csrf_token %}

      <div class="form-group row">
        <label for="bladename" class="col-sm-2 col-form-label">Name</label>
        <div class="col">
          <input
            type="text"
            class="form-control"
            value="{{ blade.name }}"
            id="bladename"
            name="bladename"
            required
          />
        </div>
      </div>
      <div class="form-group row">
        <label for="bladeip" class="col-sm-2 col-form-label">IP</label>
        <div class="col">
          <input
            type="text"
            class="form-control"
            value="{{ blade.ip }}"
            id="bladeip"
            name="bladeip"
            required
          />
        </div>
      </div>
      <div class="form-group row">
        <label for="rack" class="col-sm-2 col-form-label">Rack</label>
        <div class="col">
          <select class="custom-select" id="rack" name="rack" required>
            <option value="">choose rack...</option>
            {% for rack in racks %}
              <option value="{{ rack.id }}" {% if blade.rack.id == rack.id %} selected{% endif %}>{{ rack.name }}</option>
            {% endfor %}
          </select>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-sm-2"></div>
        <div class="col">
          <div class="row">
            <div class="col-3">
              <a href="{% url 'bladeapp:blades' %}" class="btn btn-warning btn-sm btn-block"
                >GO TO BLADE LIST</a
              >
            </div>
            <div class="col">
              <button type="submit" class="btn btn-primary btn-sm btn-block">
                UPDATE
              </button>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>

{% endblock content %}

bladeapp/templates/bladeapp/blades.html
{% extends 'sbadmin/base.html' %}{% load static %} {% block content %}

<!-- page heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h5 mb-0 text-gray-800">
    <a href="{% url 'siteapp:sites' %}">Site<a/> / 
    <a href="{% url 'rackapp:racks' %}">Rack<a/> / Blade
  </h1>
</div>

<!-- table data -->
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary"><i class="fas fa-table mr-2"></i> Blade List</h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table
        class="table table-bordered"
        id="dataTable"
        width="100%"
        cellspacing="0"
      >
        <thead>
          <tr>
            <th>#</th>
            <th>Name</th>
            <th>IP</th>
            <th>Rack</th>
            <th></th>
          </tr>
        </thead>
        <tfoot>
          <tr>
            <th></th>
            <th>Name</th>
            <th>IP</th>
            <th>Rack</th>
            <th>
              {% if adminUser %}
                <a href="{% url 'bladeapp:blade_create' %}"
                  class="btn btn-primary btn-sm btn-block">CREATE BLADE</a>
              {% else %}
                <div class="btn btn-primary btn-sm btn-block disabled customNotAllowed">CREATE BLADE</div>
							{% endif %}
              </th>
          </tr>
        </tfoot>
        <tbody>
          {% for blade in page_obj %}
          <tr>
            <td>{{ forloop.counter }}</td>
            <td>
              <a href="{% url 'bladeapp:blade_query' blade.id %}"
                class="text-primary">
                {{ blade.name }}
              </a>
            </td>
            <td>{{ blade.ip }}</td>
            <td>
              <a href="{% url 'rackapp:rack_query' blade.rack.id %}"
                class="text-primary">
                {{ blade.rack.name }}
              </a>
            </td>
            <td class="text-center">
              {% if adminUser %}
                <a href="{% url 'bladeapp:blade_update' blade.id %}"
                  class="text-info mr-4" title="edit">
                  <i class="fas fa-edit"></i>
                </a>

                <a href="#" class="text-danger ml-4" title="delete">
                  <i class="fas fa-trash-alt"></i>
                </a>
              {% else %}
                <!-- non-admin user -->
                <span class="text-info mr-4 customNotAllowed" title="edit">
                  <i class="fas fa-edit"></i>
                </span>
  
                <span class="text-danger ml-4 customNotAllowed" title="delete">
                  <i class="fas fa-trash-alt"></i>
                </span>
              {% endif %}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      {% include 'core/pagination.html' %}

    </div>
  </div>
</div>

{% endblock content %}