IPbox/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from IPbox import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    
    path('', views.ipboxHomePage, name='homepage'),
    path('sites/', include('siteapp.urls')),
    path('racks/', include('rackapp.urls')),
    path('blades/', include('bladeapp.urls')),
    path('slots/', include('slotapp.urls')),
    path('vms/', include('vmapp.urls')),
    path('clusters/', include('clusterapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bladeapp/urls.py
from django.urls import path
from . import views

# TEMPLATE TAGGING
app_name = 'bladeapp'

urlpatterns = [
  path('create', views.bladeCreate, name='blade_create'),
  path('update/<id>', views.bladeUpdate, name='blade_update'),
  path('bladequery/<id>', views.bladeQuery, name='blade_query'),
  path('', views.bladeList, name="blades"),
]

rackapp/urls.py
from django.urls import path
from . import views

# TEMPLATE TAGGING
app_name = 'rackapp'

urlpatterns = [
  path('create', views.rackCreate, name='rack_create'),
  path('update/<id>', views.rackUpdate, name='rack_update'),
  path('rackquery/<id>', views.rackQuery, name='rack_query'),
  path('', views.rackList, name="racks"),
]

siteapp/urls.py
from django.urls import path
from . import views

# TEMPLATE TAGGING
app_name = 'siteapp'

urlpatterns = [
  path('create', views.siteCreate, name='site_create'),
  path('update/<id>', views.siteUpdate, name='site_update'),
  path('sitequery/<id>', views.siteQuery, name='site_query'),
  path('', views.siteList, name="sites"),
]

slotapp/urls.py
from django.urls import path
from . import views

# TEMPLATE TAGGING
app_name = 'slotapp'

urlpatterns = [
  path('create', views.slotCreate, name='slot_create'),
  path('update/<id>', views.slotUpdate, name='slot_update'),
  path('slotquery/<id>', views.slotQuery, name='slot_query'),
  path('', views.slotList, name="slots"),
]

slotapp/models.py
from django.db import models
from bladeapp.models import Blade


class Slot(models.Model):
  name    = models.CharField(max_length=128)
  ip      = models.GenericIPAddressField()
  blade   = models.ForeignKey(Blade, related_name="slots", on_delete=models.CASCADE)

  class Meta:
    verbose_name_plural = "Slots"
    
  def __str__(self):
    return self.name

slotapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator
from django.urls import reverse

from accounts.views import generalUser, adminUser
from bladeapp.models import Blade
from .models import Slot


def slotList(request):
  dataPerPage = 5
  pageNum = request.GET.get('page', 1)
  slots = Slot.objects.all()

  p = Paginator(slots, dataPerPage)
  page_obj = p.page(pageNum)

  context = {
    'page_obj': page_obj,
    'generalUser': generalUser(request.user),
    'adminUser': adminUser(request.user)
  }
  return render(request, 'slotapp/slots.html', context)


@login_required(login_url='accountsapp:login')
def slotCreate(request):
  if not adminUser(request.user):
    return HttpResponseRedirect(reverse('homepage'))
  
  if (request.POST):
    name    = request.POST['slotname']
    ip      = request.POST['slotip']
    bladeip = request.POST['blade']
        
    blade = Blade.objects.get(pk=bladeip)
    slot  = Slot(name=name, ip=ip, blade=blade)
    slot.save()
        
    return redirect("/slots")
    
  context = {
    'blades': Blade.objects.all()
  }
  return render(request, 'slotapp/slot_create.html', context=context)


@login_required(login_url='accountsapp:login')
def slotUpdate(request, id):
  if not adminUser(request.user):
    return HttpResponseRedirect(reverse('homepage'))
  
  slot = Slot.objects.get(pk=id)
  if (request.POST):
    name    = request.POST['slotname']
    ip      = request.POST['slotip']
    bladeid = request.POST['blade']

    blade   = Blade.objects.get(pk=bladeid)
    
    slot.name = name
    slot.ip = ip
    slot.blade = blade
    slot.save()
    return redirect("/slots")
    
  context = {
    'slot': slot,
    'blades': Blade.objects.all()
  }
  return render(request, 'slotapp/slot_update.html', context=context)


@login_required(login_url='accountsapp:login')
def slotQuery(request, id):
  slot = Slot.objects.get(pk=id)

  dataPerPage = 5
  pageNum = request.GET.get('page', 1)
  vms = slot.vmslots.all()

  p = Paginator(vms, dataPerPage)
  page_obj = p.page(pageNum)

  context = {
    'page_obj': page_obj,
  }
  return render(request, 'vmapp/vms.html', context)

slotapp/templates/slotapp/slot_create.html
{% extends 'sbadmin/base.html' %} {% load static %} {% block content %}

<div class="card-body">
  <div class="container my-4">
    <h3 class="my-4">Create Slot</h3>
    <form method="POST" action="{% url 'slotapp:slot_create' %}">
      {% csrf_token %}

      <div class="form-group row">
        <label for="slotname" class="col-sm-2 col-form-label">Name</label>
        <div class="col">
          <input
            type="text"
            class="form-control"
            id="slotname"
            name="slotname"
            required
          />
        </div>
      </div>
      <div class="form-group row">
        <label for="slotip" class="col-sm-2 col-form-label">IP</label>
        <div class="col">
          <input
            type="text"
            class="form-control"
            id="slotip"
            name="slotip"
            required
          />
        </div>
      </div>
      <div class="form-group row">
        <label for="blade" class="col-sm-2 col-form-label">Blade</label>
        <div class="col">
          <select class="custom-select" id="blade" name="blade" required>
            <option value="" selected>choose blade...</option>
            {% for blade in blades %}
            <option value="{{ blade.id }}">{{ blade.name }}</option>
            {% endfor %}
          </select>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-sm-2"></div>
        <div class="col">
          <div class="row">
            <div class="col-3">
              <a href="{% url 'slotapp:slots' %}" class="btn btn-warning btn-sm btn-block">
                GO TO SLOT LIST
              </a>
            </div>
            <div class="col">
              <button type="submit" class="btn btn-primary btn-sm btn-block">
                CREATE
              </button>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>

{% endblock content %}

slotapp/templates/slotapp/slot_update.html
{% extends 'sbadmin/base.html' %} {% load static %} {% block content %}

<div class="card-body">
  <div class="container my-4">
    <h3 class="my-4">Update Slot</h3>
    <form method="POST" action="{% url 'slotapp:slot_update' slot.id %}">
      {% csrf_token %}

      <div class="form-group row">
        <label for="slotname" class="col-sm-2 col-form-label">Name</label>
        <div class="col">
          <input
            type="text"
            class="form-control"
            value="{{ slot.name }}"
            id="slotname"
            name="slotname"
            required
          />
        </div>
      </div>
      <div class="form-group row">
        <label for="slotip" class="col-sm-2 col-form-label">IP</label>
        <div class="col">
          <input
            type="text"
            class="form-control"
            value="{{ slot.ip }}"
            id="slotip"
            name="slotip"
            required
          />
        </div>
      </div>
      <div class="form-group row">
        <label for="blade" class="col-sm-2 col-form-label">Blade</label>
        <div class="col">
          <select class="custom-select" id="blade" name="blade" required>
            <option value="">choose blade...</option>
            {% for blade in blades %}
              <option value="{{ blade.id }}" {% if slot.blade.id == blade.id %} selected {% endif %}>{{ blade.name }}</option>
            {% endfor %}
          </select>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-sm-2"></div>
        <div class="col">
          <div class="row">
            <div class="col-3">
              <a href="{% url 'slotapp:slots' %}" class="btn btn-warning btn-sm btn-block">
                GO TO SLOT LIST
              </a>
            </div>
            <div class="col">
              <button type="submit" class="btn btn-primary btn-sm btn-block">
                UPDATE
              </button>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>

{% endblock content %}

slotapp/templates/slotapp/slots.html
{% extends 'sbadmin/base.html' %}{% load static %} {% block content %}

<!-- page heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h5 mb-0 text-gray-800">
    <a href="{% url 'siteapp:sites' %}">Site<a/> / 
    <a href="{% url 'rackapp:racks' %}">Rack<a/> / 
    <a href="{% url 'bladeapp:blades' %}">Blade<a/> / Slot
  </h1>
</div>

<!-- table data -->
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary"><i class="fas fa-table mr-2"></i> Slot List</h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table
        class="table table-bordered"
        id="dataTable"
        width="100%"
        cellspacing="0"
      >
        <thead>
          <tr>
            <th>#</th>
            <th>Name</th>
            <th>IP</th>
            <th>Blade</th>
            <th></th>
          </tr>
        </thead>
        <tfoot>
          <tr>
            <th></th>
            <th>Name</th>
            <th>IP</th>
            <th>Blade</th>
            <th>
              {% if adminUser %}
                <a href="{% url 'slotapp:slot_create' %}"
                  class="btn btn-primary btn-sm btn-block">CREATE SLOT</a>
              {% else %}
                <div class="btn btn-primary btn-sm btn-block disabled customNotAllowed">CREATE SLOT</div>
							{% endif %}
            </th>
          </tr>
        </tfoot>
        <tbody>
          {% for slot in page_obj %}
          <tr>
            <td>{{ forloop.counter }}</td>
            <td>
              <a href="{% url 'slotapp:slot_query' slot.id %}"
                class="text-primary">
                {{ slot.name }}
              </a>
            </td>
            <td>{{ slot.ip }}</td>
            <td>
              <a href="{% url 'bladeapp:blade_query' slot.blade.id %}"
                class="text-primary">
                {{ slot.blade.name }}
              </a>
            </td>
            <td class="text-center">
              {% if adminUser %}
                <a href="{% url 'slotapp:slot_update' slot.id %}"
                  class="text-info mr-4" title="edit">
                  <i class="fas fa-edit"></i>
                </a>

                <a href="#" class="text-danger ml-4" title="delete">
                  <i class="fas fa-trash-alt"></i>
                </a>
              {% else %}
                <!-- non-admin user -->
                <span class="text-info mr-4 customNotAllowed" title="edit">
                  <i class="fas fa-edit"></i>
                </span>
  
                <span class="text-danger ml-4 customNotAllowed" title="delete">
                  <i class="fas fa-trash-alt"></i>
                </span>
              {% endif %}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      {% include 'core/pagination.html' %}

    </div>
  </div>
</div>

{% endblock content %}