IPbox/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from IPbox import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    
    path('', views.ipboxHomePage, name='homepage'),
    path('sites/', include('siteapp.urls')),
    path('racks/', include('rackapp.urls')),
    path('blades/', include('bladeapp.urls')),
    path('slots/', include('slotapp.urls')),
    path('vms/', include('vmapp.urls')),
    path('clusters/', include('clusterapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bladeapp/urls.py
from django.urls import path
from . import views

# TEMPLATE TAGGING
app_name = 'bladeapp'

urlpatterns = [
  path('create', views.bladeCreate, name='blade_create'),
  path('update/<id>', views.bladeUpdate, name='blade_update'),
  path('bladequery/<id>', views.bladeQuery, name='blade_query'),
  path('', views.bladeList, name="blades"),
]

clusterapp/urls.py
from django.urls import path
from . import views

# TEMPLATE TAGGING
app_name = 'clusterapp'

urlpatterns = [
  path('create', views.clusterCreate, name='cluster_create'),
  path('update/<id>', views.clusterUpdate, name='cluster_update'),
  path('clusterquery/<id>', views.clusterQuery, name='cluster_query'),
  path('', views.clusterList, name="clusters"),
]

rackapp/urls.py
from django.urls import path
from . import views

# TEMPLATE TAGGING
app_name = 'rackapp'

urlpatterns = [
  path('create', views.rackCreate, name='rack_create'),
  path('update/<id>', views.rackUpdate, name='rack_update'),
  path('rackquery/<id>', views.rackQuery, name='rack_query'),
  path('', views.rackList, name="racks"),
]

siteapp/urls.py
from django.urls import path
from . import views

# TEMPLATE TAGGING
app_name = 'siteapp'

urlpatterns = [
  path('create', views.siteCreate, name='site_create'),
  path('update/<id>', views.siteUpdate, name='site_update'),
  path('sitequery/<id>', views.siteQuery, name='site_query'),
  path('', views.siteList, name="sites"),
]

slotapp/urls.py
from django.urls import path
from . import views

# TEMPLATE TAGGING
app_name = 'slotapp'

urlpatterns = [
  path('create', views.slotCreate, name='slot_create'),
  path('update/<id>', views.slotUpdate, name='slot_update'),
  path('slotquery/<id>', views.slotQuery, name='slot_query'),
  path('', views.slotList, name="slots"),
]

clusterapp/models.py
from django.db import models

class Cluster(models.Model):
  name        = models.CharField(max_length=128)
  ip          = models.GenericIPAddressField()
  lb_ip       = models.GenericIPAddressField()
  bootstrap   = models.GenericIPAddressField()

  class Meta:
    verbose_name_plural = "Clusters"
    
  def __str__(self):
    return self.name

clusterapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator
from django.urls import reverse

from accounts.views import generalUser, adminUser
from slotapp.models import Slot
from vmapp.models import VM
from .models import Cluster


def clusterList(request):
  dataPerPage = 5
  pageNum = request.GET.get('page', 1)
  clusters = Cluster.objects.all()

  p = Paginator(clusters, dataPerPage)
  page_obj = p.page(pageNum)

  context = {
    'page_obj': page_obj,
    'generalUser': generalUser(request.user),
    'adminUser': adminUser(request.user)
  }
  return render(request, 'clusterapp/clusters.html', context)


@login_required(login_url='accountsapp:login')
def clusterCreate(request):
  if not adminUser(request.user):
    return HttpResponseRedirect(reverse('homepage'))
  
  if (request.POST):
    name      = request.POST['clustername']
    ip        = request.POST['clusterip']
    lb_ip     = request.POST['clusterlb_ip']
    bootstrap = request.POST['clusterbootstrap']
        
    cluster = Cluster(name=name, ip=ip, lb_ip=lb_ip, bootstrap=bootstrap)
    cluster.save()
    return redirect("/clusters")
  
  return render(request, 'clusterapp/cluster_create.html')


@login_required(login_url='accountsapp:login')
def clusterUpdate(request, id):
  if not adminUser(request.user):
    return HttpResponseRedirect(reverse('homepage'))

  cluster = Cluster.objects.get(pk=id)
  if (request.POST):
    name      = request.POST['clustername']
    ip        = request.POST['clusterip']
    lb_ip     = request.POST['clusterlb_ip']
    bootstrap = request.POST['clusterbootstrap']
        
    cluster.name = name
    cluster.ip = ip
    cluster.lb_ip = lb_ip
    cluster.bootstrap = bootstrap
        
    cluster.save()
    return redirect("/clusters")
    
  context = {
    'cluster': cluster,
  }
  return render(request, 'clusterapp/cluster_update.html', context=context)


def clusterQuery(request, id):
  pass

clusterapp/templates/clusterapp/cluster_create.html
{% extends 'sbadmin/base.html' %} {% load static %} {% block content %}

<div class="card-body">
  <div class="container my-4">
    <h3 class="my-4">Create Cluster</h3>
    <form method="POST" action="{% url 'clusterapp:cluster_create' %}">
      {% csrf_token %}

      <div class="form-group row">
        <label for="clustername" class="col-sm-2 col-form-label">Name</label>
        <div class="col">
          <input
            type="text"
            class="form-control"
            id="clustername"
            name="clustername"
            required
          />
        </div>
      </div>
      <div class="form-group row">
        <label for="clusterip" class="col-sm-2 col-form-label">IP</label>
        <div class="col">
          <input
            type="text"
            class="form-control"
            id="clusterip"
            name="clusterip"
            required
          />
        </div>
      </div>
      <div class="form-group row">
        <label for="clusterlb_ip" class="col-sm-2 col-form-label">LB IP</label>
        <div class="col">
          <input
            type="text"
            class="form-control"
            id="clusterlb_ip"
            name="clusterlb_ip"
            required
          />
        </div>
      </div>
      <div class="form-group row">
        <label for="clusterbootstrap" class="col-sm-2 col-form-label"
          >Bootstrap IP</label
        >
        <div class="col">
          <input
            type="text"
            class="form-control"
            id="clusterbootstrap"
            name="clusterbootstrap"
            required
          />
        </div>
      </div>

      <div class="form-group row">
        <div class="col-sm-2"></div>
        <div class="col">
          <div class="row">
            <div class="col-3">
              <a href="{% url 'clusterapp:clusters' %}" class="btn btn-warning btn-sm btn-block"
                >GO TO CLUSTER LIST</a
              >
            </div>
            <div class="col">
              <button type="submit" class="btn btn-primary btn-sm btn-block">
                CREATE
              </button>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>

{% endblock content %}

clusterapp/templates/clusterapp/cluster_update.html
{% extends 'sbadmin/base.html' %} {% load static %} {% block content %}

<div class="card-body">
  <div class="container my-4">
    <h3 class="my-4">Update Cluster</h3>
    <form method="POST" action="{% url 'clusterapp:cluster_update' cluster.id %}">
      {% csrf_token %}

      <div class="form-group row">
        <label for="clustername" class="col-sm-2 col-form-label">Name</label>
        <div class="col">
          <input
            type="text"
            class="form-control"
            value="{{ cluster.name }}"
            id="clustername"
            name="clustername"
            required
          />
        </div>
      </div>
      <div class="form-group row">
        <label for="clusterip" class="col-sm-2 col-form-label">IP</label>
        <div class="col">
          <input
            type="text"
            class="form-control"
            value="{{ cluster.ip }}"
            id="clusterip"
            name="clusterip"
            required
          />
        </div>
      </div>
      <div class="form-group row">
        <label for="clusterlb_ip" class="col-sm-2 col-form-label">LB IP</label>
        <div class="col">
          <input
            type="text"
            class="form-control"
            value="{{ cluster.lb_ip }}"
            id="clusterlb_ip"
            name="clusterlb_ip"
            required
          />
        </div>
      </div>
      <div class="form-group row">
        <label for="clusterbootstrap" class="col-sm-2 col-form-label"
          >Bootstrap IP</label
        >
        <div class="col">
          <input
            type="text"
            class="form-control"
            value="{{ cluster.bootstrap }}"
            id="clusterbootstrap"
            name="clusterbootstrap"
            required
          />
        </div>
      </div>

      <div class="form-group row">
        <div class="col-sm-2"></div>
        <div class="col">
          <div class="row">
            <div class="col-3">
              <a href="{% url 'clusterapp:clusters' %}" class="btn btn-warning btn-sm btn-block"
                >GO TO CLUSTER LIST</a
              >
            </div>
            <div class="col">
              <button type="submit" class="btn btn-primary btn-sm btn-block">
                UPDATE
              </button>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>

{% endblock content %}

clusterapp/templates/clusterapp/clusters.html
{% extends 'sbadmin/base.html' %}{% load static %} {% block content %}

<!-- page heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h5 mb-0 text-gray-800">
    <a href="{% url 'siteapp:sites' %}">Site<a/> / 
    <a href="{% url 'rackapp:racks' %}">Rack<a/> / 
    <a href="{% url 'bladeapp:blades' %}">Blade<a/> / 
    <a href="{% url 'slotapp:slots' %}">Slot<a/> / Cluster
  </h1>
</div>

<!-- table data -->
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary"><i class="fas fa-table mr-2"></i> Cluster List</h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table
        class="table table-bordered"
        id="dataTable"
        width="100%"
        cellspacing="0"
      >
        <thead>
          <tr>
            <th>#</th>
            <th>Name</th>
            <th>IP</th>
            <th>LB IP</th>
            <th>Bootstrap</th>
            <th></th>
          </tr>
        </thead>
        <tfoot>
          <tr>
            <th></th>
            <th>Name</th>
            <th>IP</th>
            <th>LB IP</th>
            <th>Bootstrap</th>
            <th>
              {% if adminUser %}
                <a href="{% url 'clusterapp:cluster_create' %}"
                  class="btn btn-primary btn-sm btn-block">CREATE CLUSTER</a>
              {% else %}
                <div class="btn btn-primary btn-sm btn-block disabled customNotAllowed">CREATE CLUSTER</div>
              {% endif %}
            </th>
          </tr>
        </tfoot>
        <tbody>
          {% for cluster in page_obj %}
          <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ cluster.name }}</td>
            <td>{{ cluster.ip }}</td>
            <td>{{ cluster.lb_ip }}</td>
            <td>{{ cluster.bootstrap }}</td>
            <td class="text-center">
              {% if adminUser %}
                <a href="{% url 'clusterapp:cluster_update' cluster.id %}"
                  class="text-info mr-4" title="edit">
                  <i class="fas fa-edit"></i>
                </a>

                <a href="#" class="text-danger ml-4" title="delete">
                  <i class="fas fa-trash-alt"></i>
                </a>
              {% else %}
                <!-- non-admin user -->
                <span class="text-info mr-4 customNotAllowed" title="edit">
                  <i class="fas fa-edit"></i>
                </span>
  
                <span class="text-danger ml-4 customNotAllowed" title="delete">
                  <i class="fas fa-trash-alt"></i>
                </span>
              {% endif %}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      {% include 'core/pagination.html' %}

    </div>
  </div>
</div>

{% endblock content %}